FROM postgres:14.1

RUN apt-get update && apt-get  install -y postgresql-14

CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]
# FROM library/postgres
# COPY init.sql /docker-entrypoint-initdb.d/

