# Generated by Django 5.1 on 2024-08-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintehtest', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
